# Generated by Django 4.2.7 on 2025-11-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Patient's full name", max_length=200),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Patient's contact number", max_length=15
                    ),
                ),
                (
                    "mail_id",
                    models.EmailField(
                        help_text="Patient's email address", max_length=254
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(help_text="Doctor's name", max_length=200),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Medical department/specialization", max_length=100
                    ),
                ),
                ("appointment_date", models.DateField(help_text="Date of appointment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient Record",
                "verbose_name_plural": "Patient Records",
                "db_table": "patient_record",
                "ordering": ["-appointment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking_id"], name="patient_rec_booking_ea5148_idx"
                    ),
                    models.Index(
                        fields=["phone_number"], name="patient_rec_phone_n_a9c4bb_idx"
                    ),
                    models.Index(
                        fields=["appointment_date"],
                        name="patient_rec_appoint_d08288_idx",
                    ),
                ],
            },
        ),
    ]
