# Generated by Django 4.2.7 on 2025-11-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_add_appointment_history_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Appointment Confirmation"),
                            ("reminder", "Appointment Reminder"),
                            ("cancellation", "Cancellation Notice"),
                            ("reschedule", "Reschedule Notice"),
                        ],
                        default="confirmation",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("message_body", models.TextField()),
                (
                    "message_sid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("undelivered", "Undelivered"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_doctor__221180_idx",
            old_name="appointment_doctor__idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_status_8fe9d7_idx",
            old_name="appointment_status_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_patient_412fa9_idx",
            old_name="appointment_patient_idx",
        ),
        migrations.AddField(
            model_name="smsnotification",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_notifications",
                to="appointments.appointment",
            ),
        ),
        migrations.AddIndex(
            model_name="smsnotification",
            index=models.Index(
                fields=["appointment", "notification_type"],
                name="appointment_appoint_80b09c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smsnotification",
            index=models.Index(
                fields=["message_sid"], name="appointment_message_1777f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsnotification",
            index=models.Index(fields=["status"], name="appointment_status_1f66b5_idx"),
        ),
    ]
