# Generated by Django 4.2.7 on 2025-11-16 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoiceConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("stage", models.CharField(default="greeting", max_length=50)),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "patient_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("doctor_id", models.IntegerField(blank=True, null=True)),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                ("appointment_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="voicebot_vo_session_3b5050_idx"
                    ),
                    models.Index(
                        fields=["completed"], name="voicebot_vo_complet_9f7977_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("intent", models.CharField(blank=True, max_length=50, null=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="voicebot.voiceconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "timestamp"],
                        name="voicebot_co_convers_8c4587_idx",
                    )
                ],
            },
        ),
    ]
